version: "3.5"
services:
  db:
    image: 'postgres:13'
    container_name: 'db'
    networks:
      - backend
    env_file: ./env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    container_name: 'rabbitmq'
    networks:
      - backend
    ports:
      - '15672:15672'
    env_file:
      - ./env/.rabbitmq.env
    restart: unless-stopped

  redis:
    image: 'redis:7'
    container_name: 'redis'
    networks:
      - backend
    volumes:
      - cache_data:/data
    restart: unless-stopped

  online_shop:
    build: .
    container_name: 'online_shop'
    image: 'online_shop:1'
    command: >
      sh -c 'cd src &&
             poetry run python3 manage.py migrate --no-input &&
             poetry run python3 manage.py createadmin &&
             poetry run python3 manage.py runserver 0.0.0.0:8080'
    networks:
      - backend
    ports:
      - '8080:8080'
    volumes:
      - ./src:/service/src
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.online_shop.env
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - rabbitmq

  payment:
    image: 'stripe/stripe-cli'
    container_name: 'payment'
    command: "listen --forward-to 0.0.0.0:8080/payment/webhook/"
    network_mode: "host"
    depends_on:
      - online_shop
    restart: unless-stopped

  worker1:
    build: .
    container_name: 'worker1'
    command: >
      sh -c "cd src && 
             poetry run celery -A celery_app.app worker --loglevel=info"
    networks:
      - backend
    volumes:
      - ./src:/service/src
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.online_shop.env
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - online_shop

networks:
  backend:

volumes:
  postgres_data:
  cache_data:
  app_static:
  app_media: