# Generated by Django 4.2.6 on 2023-10-15 13:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('only_available', django.db.models.manager.Manager()),
            ],
        ),
    ]
